/*
	see comment in PICOMMON.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#define LIBNDS_STRINGIFY(x) LIBNDS_STRINGIFY_(x)
#define LIBNDS_STRINGIFY_(x) #x

#define ITCM_CODE __attribute__((__section__(".itcm.text." __FILE__ "." LIBNDS_STRINGIFY(__LINE__)), __long_call__))
#define DTCM_DATA __attribute__((__section__(".dtcm." __FILE__ "." LIBNDS_STRINGIFY(__LINE__))))
#define RAM_CODE __attribute__( ( __section__( ".text" ) ) )

#define ARM_CODE __attribute__((__target__("arm")))
#define THUMB_CODE __attribute__((__target__("thumb")))
