/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <nds.h>
#include <fat.h>
#include <filesystem.h>
#include <nds/arm9/dldi.h>
#include <maxmod9.h>
#include <assert.h>

#define CanGetAppPath 1
#define HaveAppPathLink 1
#define HaveSysctlPath 0

#define EnableDragDrop 1
#define WantOSGLUDSI 1

#define kStrAppName "Mini vMac"
#define kAppVariationStr "minivmac-37.03-larm"
#define kStrCopyrightYear "2020"
#define kMaintainerName "unknown"
#define kStrHomePage "(unknown)"
