// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Mini vMac

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_uiTabPageDisplay;
extern lv_obj_t *ui_Label15;
extern void ui_event_uiSwitchSubpixelMode( lv_event_t * e);
extern lv_obj_t *ui_uiSwitchSubpixelMode;
extern lv_obj_t *ui_Label1;
extern void ui_event_uiDropdownSubpxTop( lv_event_t * e);
extern lv_obj_t *ui_uiDropdownSubpxTop;
extern lv_obj_t *ui_Label2;
extern void ui_event_uiDropdownSubpxBottom( lv_event_t * e);
extern lv_obj_t *ui_uiDropdownSubpxBottom;
extern lv_obj_t *ui_Label4;
extern void ui_event_uiSwitchScale( lv_event_t * e);
extern lv_obj_t *ui_uiSwitchScale;
extern lv_obj_t *ui_Label3;
extern void ui_event_uiSwitchInvert( lv_event_t * e);
extern lv_obj_t *ui_uiSwitchInvert;
extern lv_obj_t *ui_uiTabPageEmulator;
extern lv_obj_t *ui_Label9;
extern void ui_event_uiDropdownEmuSpeed( lv_event_t * e);
extern lv_obj_t *ui_uiDropdownEmuSpeed;
extern lv_obj_t *ui_Label10;
extern void ui_event_uiSwitchSound( lv_event_t * e);
extern lv_obj_t *ui_uiSwitchSound;
extern void ui_event_uiButtonReset( lv_event_t * e);
extern lv_obj_t *ui_uiButtonReset;
extern lv_obj_t *ui_Label11;
extern void ui_event_uiButtonExit( lv_event_t * e);
extern lv_obj_t *ui_uiButtonExit;
extern lv_obj_t *ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

