// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Mini vMac

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void uiDisplayTabValueChangedCallback(lv_event_t * e);
void uiEmulatorTabValueChangedCallback(lv_event_t * e);
void uiCallbackEmulatorReset(lv_event_t * e);
void uiCallbackEmulatorExit(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
