#ifndef _UI_SELECTIONS_H_
#define _UI_SELECTIONS_H_

typedef enum {
    UI_SEL_MOUSE_MODE_SCALED = 0,
    UI_SEL_MOUSE_MODE_TRACKPAD,
    UI_SEL_MOUSE_MODE_DPAD,
    UI_SEL_MOUSE_MODE_ABXY
} UIMouseMode;

typedef enum {
    UI_SEL_MOUSE_BUTTON_LEFT = 0,
    UI_SEL_MOUSE_BUTTON_RIGHT,
    UI_SEL_MOUSE_BUTTON_UP,
    UI_SEL_MOUSE_BUTTON_DOWN,
    UI_SEL_MOUSE_BUTTON_A,
    UI_SEL_MOUSE_BUTTON_B,
    UI_SEL_MOUSE_BUTTON_X,
    UI_SEL_MOUSE_BUTTON_Y,
    UI_SEL_MOUSE_BUTTON_L,
    UI_SEL_MOUSE_BUTTON_R
} UIMouseButton;

typedef enum {
    UI_SEL_EMULATOR_SPEED_1X = 0,
    UI_SEL_EMULATOR_SPEED_2X,
    UI_SEL_EMULATOR_SPEED_UNLIMITED
} UIEmulatorSpeed;

typedef enum {
    UI_SEL_SUBPX_ORDER_RGB = 0,
    UI_SEL_SUBPX_ORDER_BGR
} UISubpxOrder;

#endif
